version: "3.8"
services:
  mysql1:
    build: ./compose/mysql-service-test
    volumes:
      - ./local/mysql:/var/lib/mysql
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      DATABASE_PASSWORD: root
    expose:
      - "3306"
    ports:
      - "3306:3306"

  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    # command: npm start
    networks:
      - app-network
    depends_on:
      - mysql1
    links:
      - mysql1
    ports:
      - "9090:9090"
    volumes:
      - ./src:/app/src
    environment:
      - DATABASE_HOST=mysql1
      - DATABASE_PORT=3306
      - NODE_ENV=production
      - DATABASE_PASSWORD=root
      - DATABASE_USER=root
      - DATABASE_DB_NAME=test

networks:
  app-network:
    driver: bridge
